/**
 * Env lengkap dan deterministik untuk unit/integration test apps/api.
 *
 * Integration suite menimpa DATABASE_URL dengan TEST_DATABASE_URL. Tidak ada
 * secret produksi dan tidak membaca file `.env` pribadi developer.
 */
const testDatabaseUrl =
  process.env.TEST_DATABASE_URL ?? 'postgres://hola:hola@localhost:5432/hola_test'

Object.assign(process.env, {
  NODE_ENV: 'test',
  APP_ENV: 'local',
  PORT: '4000',
  API_BASE_URL: 'http://localhost:4000',
  WEB_BASE_URL: 'http://localhost:3000',
  ADMIN_BASE_URL: 'http://localhost:3001',
  CORS_ORIGINS: 'http://localhost:3000,http://localhost:3001',
  DATABASE_URL: testDatabaseUrl,
  DATABASE_POOL_MAX: '2',
  REDIS_URL: process.env.TEST_REDIS_URL ?? 'redis://localhost:6379',
  JWT_ACCESS_SECRET: 'test-jwt-secret-minimal-32-byte-random',
  JWT_ACCESS_TTL: '15m',
  REFRESH_TOKEN_TTL_DAYS: '30',
  PASSWORD_PEPPER: 'test-password-pepper',
  COOKIE_DOMAIN: 'localhost',
  TZ_BUSINESS: 'Asia/Makassar',
  SLOT_HOLD_TTL_SECONDS: '600',
  PAYMENT_EXPIRY_MINUTES: '15',
  MIDTRANS_SERVER_KEY: 'test-midtrans-server',
  MIDTRANS_CLIENT_KEY: 'test-midtrans-client',
  MIDTRANS_MERCHANT_ID: 'test-merchant',
  MIDTRANS_IS_PRODUCTION: 'false',
  MIDTRANS_WEBHOOK_ALLOWED_IPS: '',
  S3_ENDPOINT: 'http://localhost:9000',
  S3_REGION: 'auto',
  S3_ACCESS_KEY_ID: 'test-access-key',
  S3_SECRET_ACCESS_KEY: 'test-secret-key',
  S3_BUCKET_MEDIA: 'hola-media',
  S3_BUCKET_PRIVATE: 'hola-private',
  S3_BUCKET_BACKUP: 'hola-backup',
  S3_FORCE_PATH_STYLE: 'true',
  MEDIA_PUBLIC_BASE_URL: 'http://localhost:9000/hola-media',
  MAIL_TRANSPORT: 'console',
  RESEND_API_KEY: '',
  MAIL_FROM: 'Hola <noreply@hola.test>',
  SMTP_HOST: 'localhost',
  SMTP_PORT: '1025',
  SMTP_USER: '',
  SMTP_PASS: '',
  EXPO_ACCESS_TOKEN: 'test-expo-token',
  NOTIF_WHATSAPP_ENABLED: 'false',
  WHATSAPP_PROVIDER: '',
  WHATSAPP_API_KEY: '',
  WHATSAPP_SENDER: '',
  SENTRY_DSN: '',
  SENTRY_TRACES_SAMPLE_RATE: '0.1',
  LOG_LEVEL: process.env.LOG_LEVEL ?? 'fatal',
  RATE_LIMIT_ENABLED: 'true',
  INTERNAL_TOKEN: 'test-internal-token-minimal-32-bytes',
  BULLBOARD_USER: 'test-admin',
  BULLBOARD_PASSWORD: 'test-password',
  BACKUP_ENABLED: 'false',
  BACKUP_RETENTION_DAYS: '30',
})
