/**
 * Test drift: katalog kode ≡ docs/04-API-CONTRACT.md § 5.
 *
 * DOC_ERRORS dan DOC_WARNINGS adalah SALINAN VERBATIM kolom tabel dokumen.
 * Saat dokumen berubah, salin ulang barisnya ke sini.
 */
import { describe, expect, it } from 'vitest'
import { ERROR_CODE, ERROR_HTTP_STATUS, WARNING_CODE } from './error-codes.ts'

const DOC_ERRORS = `
VALIDATION_ERROR 422
MALFORMED_REQUEST 400
UNAUTHENTICATED 401
TOKEN_EXPIRED 401
TOKEN_REVOKED 401
FORBIDDEN 403
NOT_RESOURCE_OWNER 403
NOT_FOUND 404
METHOD_NOT_ALLOWED 405
CONFLICT 409
GONE 410
RATE_LIMITED 429
IDEMPOTENCY_KEY_REUSED 409
PRECONDITION_FAILED 409
INTERNAL_ERROR 500
SERVICE_UNAVAILABLE 503
UPSTREAM_ERROR 502
FEATURE_DISABLED 403
SLOT_ALREADY_CLAIMED 409
SLOT_NOT_ALIGNED 422
SLOT_OUTSIDE_OPERATING_HOURS 422
SLOT_IN_PAST 422
SLOT_TOO_FAR_AHEAD 422
SLOTS_NOT_CONTIGUOUS 422
SLOT_COUNT_OUT_OF_RANGE 422
COURT_NOT_BOOKABLE 422
COURT_HAS_FUTURE_CLAIMS 422
VENUE_CLOSED 422
MIXED_BOOKING_DATE 422
PRICE_RULE_NOT_FOUND 422
QUOTE_ITEM_LIMIT_EXCEEDED 422
ADDON_NOT_APPLICABLE 422
BOOKING_HOLD_EXPIRED 410
BOOKING_NOT_CANCELLABLE 409
BOOKING_ALREADY_PAID 409
BOOKING_ALREADY_CANCELLED 409
BOOKING_ALREADY_CHECKED_IN 409
BOOKING_NOT_CHECKED_IN 409
GUEST_CONTACT_REQUIRED 422
PAYMENT_NOT_PENDING 409
PAYMENT_ALREADY_PAID 409
PAYMENT_EXPIRED 410
PAYMENT_AMOUNT_MISMATCH 422
PAYMENT_METHOD_UNSUPPORTED 422
WEBHOOK_SIGNATURE_INVALID 401
WEBHOOK_UNKNOWN_ORDER 404
REFUND_NOT_ALLOWED 409
REFUND_AMOUNT_EXCEEDS_PAYMENT 422
REFUND_ALREADY_COMPLETED 409
PROMO_NOT_FOUND 404
PROMO_INACTIVE 422
PROMO_NOT_STARTED 422
PROMO_EXPIRED 410
PROMO_QUOTA_EXHAUSTED 409
PROMO_USER_QUOTA_EXHAUSTED 409
PROMO_MIN_TRANSACTION_NOT_MET 422
PROMO_NOT_APPLICABLE 422
PROMO_NOT_STACKABLE 409
PROMO_NEW_CUSTOMER_ONLY 422
EVENT_NOT_PUBLISHED 404
EVENT_REGISTRATION_NOT_OPEN 409
EVENT_FULL 409
EVENT_WAITLIST_FULL 409
EVENT_ALREADY_REGISTERED 409
EVENT_REGISTRATION_NOT_CANCELLABLE 409
EVENT_HAS_REGISTRATIONS 409
EVENT_SCHEDULE_REQUIRED 422
TOURNAMENT_REGISTRATION_NOT_OPEN 409
TOURNAMENT_FULL 409
TOURNAMENT_ALREADY_REGISTERED 409
TOURNAMENT_MIN_PARTICIPANTS_NOT_MET 422
TOURNAMENT_BRACKET_ALREADY_GENERATED 409
TOURNAMENT_BRACKET_NOT_GENERATED 409
TOURNAMENT_FORMAT_UNSUPPORTED 422
MATCH_NOT_SCHEDULABLE 409
MATCH_ALREADY_COMPLETED 409
MATCH_SCORE_INVALID 422
MATCH_PARTICIPANTS_INCOMPLETE 409
MATCH_WALKOVER_REQUIRES_REASON 422
POINT_RULE_NOT_FOUND 404
POINT_CAP_REACHED 409
POINT_ADJUSTMENT_REQUIRES_REASON 422
LEADERBOARD_PERIOD_CLOSED 409
CAFE_UNIT_OCCUPIED 409
CAFE_CONTRACT_NOT_ACTIVE 409
CAFE_INVOICE_ALREADY_PAID 409
CAFE_INVOICE_VOID 409
CAFE_PAYMENT_EXCEEDS_INVOICE 422
JOURNAL_NOT_BALANCED 422
JOURNAL_ALREADY_POSTED 409
JOURNAL_PERIOD_LOCKED 409
ACCOUNT_INACTIVE 422
ATTENDANCE_ALREADY_CLOCKED_IN 409
ATTENDANCE_NOT_CLOCKED_IN 409
SHIFT_ASSIGNMENT_CONFLICT 409
MEDIA_KIND_UNSUPPORTED 422
MEDIA_CONTENT_TYPE_UNSUPPORTED 422
MEDIA_TOO_LARGE 422
MEDIA_NOT_UPLOADED 409
STORAGE_UNAVAILABLE 502
`

const DOC_WARNINGS = `
PRICE_CHANGED
PROMO_QUOTA_EXHAUSTED
PROMO_NOT_FOUND
PROMO_NOT_APPLICABLE
PROMO_SUPERSEDED_BY_BETTER_OFFER
DISCOUNT_CLAMPED
BEYOND_BOOKING_HORIZON
COUNT_OMITTED_FOR_PERFORMANCE
STANDINGS_NOT_APPLICABLE
SLOT_OUTSIDE_OPERATING_HOURS
TIE_UNRESOLVED
WORKER_DEGRADED
`

const docErrors = DOC_ERRORS.trim()
  .split('\n')
  .map((line) => {
    const [code, http] = line.trim().split(' ')
    if (code === undefined || http === undefined) {
      throw new Error(`Baris DOC_ERRORS tidak dapat diurai: ${line}`)
    }
    return { code, http: Number(http) }
  })

const docWarnings = DOC_WARNINGS.trim()
  .split('\n')
  .map((line) => line.trim())

describe('error-codes ≡ docs/04-API-CONTRACT.md § 5', () => {
  it('jumlah kode error sama persis', () => {
    expect(Object.keys(ERROR_HTTP_STATUS)).toHaveLength(docErrors.length)
  })

  it('jumlah warning code sama persis', () => {
    expect(Object.keys(WARNING_CODE)).toHaveLength(docWarnings.length)
  })

  it('ERROR_CODE memuat gabungan error + warning tanpa duplikat', () => {
    const union = new Set([...docErrors.map((e) => e.code), ...docWarnings])
    expect(Object.keys(ERROR_CODE).sort()).toEqual([...union].sort())
  })

  it('setiap kunci ERROR_CODE bernilai sama dengan namanya', () => {
    const mismatched = Object.entries(ERROR_CODE).filter(([k, v]) => k !== v)
    expect(mismatched).toEqual([])
  })

  it('warning code berbagi ruang nama dengan ERROR_CODE (docs/04 § 5)', () => {
    const notInErrorCode = docWarnings.filter((w) => !(w in ERROR_CODE))
    expect(notInErrorCode).toEqual([])
  })

  describe.each(docErrors)('$code', ({ code, http }) => {
    it(`HTTP ${http} sesuai dokumen`, () => {
      expect(ERROR_HTTP_STATUS[code as keyof typeof ERROR_HTTP_STATUS]).toBe(http)
    })
  })
})
