/**
 * Katalog kode error & warning.
 *
 * Sumber kebenaran: docs/04-API-CONTRACT.md § 5 ("Katalog error code" dan
 * "Katalog warning code"). Test drift error-codes.test.ts menjaga file ini tetap
 * identik dengan dokumen.
 *
 * Warning memakai RUANG NAMA YANG SAMA dengan error (docs/04 § 5, kalimat
 * penutup): satu kode tidak pernah berarti dua hal berbeda. Karena itu keduanya
 * hidup di satu objek ERROR_CODE; WARNING_CODE hanya menandai bagian mana yang
 * boleh muncul di `meta.warnings` pada response 2xx.
 *
 * Jangan pernah menulis kode error sebagai string literal di service
 * (docs/16-CONVENTIONS.md AI-6).
 */

export const ERROR_CODE = {
  // ── Umum ────────────────────────────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_RESOURCE_OWNER: 'NOT_RESOURCE_OWNER',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  GONE: 'GONE',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  // ── Slot & Court ────────────────────────────────────────────────────────────
  SLOT_ALREADY_CLAIMED: 'SLOT_ALREADY_CLAIMED',
  SLOT_NOT_ALIGNED: 'SLOT_NOT_ALIGNED',
  SLOT_OUTSIDE_OPERATING_HOURS: 'SLOT_OUTSIDE_OPERATING_HOURS',
  SLOT_IN_PAST: 'SLOT_IN_PAST',
  SLOT_TOO_FAR_AHEAD: 'SLOT_TOO_FAR_AHEAD',
  SLOTS_NOT_CONTIGUOUS: 'SLOTS_NOT_CONTIGUOUS',
  SLOT_COUNT_OUT_OF_RANGE: 'SLOT_COUNT_OUT_OF_RANGE',
  COURT_NOT_BOOKABLE: 'COURT_NOT_BOOKABLE',
  COURT_HAS_FUTURE_CLAIMS: 'COURT_HAS_FUTURE_CLAIMS',
  VENUE_CLOSED: 'VENUE_CLOSED',
  MIXED_BOOKING_DATE: 'MIXED_BOOKING_DATE',
  // ── Pricing ─────────────────────────────────────────────────────────────────
  PRICE_RULE_NOT_FOUND: 'PRICE_RULE_NOT_FOUND',
  QUOTE_ITEM_LIMIT_EXCEEDED: 'QUOTE_ITEM_LIMIT_EXCEEDED',
  ADDON_NOT_APPLICABLE: 'ADDON_NOT_APPLICABLE',
  // ── Booking ─────────────────────────────────────────────────────────────────
  BOOKING_HOLD_EXPIRED: 'BOOKING_HOLD_EXPIRED',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  BOOKING_ALREADY_PAID: 'BOOKING_ALREADY_PAID',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_ALREADY_CHECKED_IN: 'BOOKING_ALREADY_CHECKED_IN',
  BOOKING_NOT_CHECKED_IN: 'BOOKING_NOT_CHECKED_IN',
  GUEST_CONTACT_REQUIRED: 'GUEST_CONTACT_REQUIRED',
  // ── Payment & Refund ────────────────────────────────────────────────────────
  PAYMENT_NOT_PENDING: 'PAYMENT_NOT_PENDING',
  PAYMENT_ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_METHOD_UNSUPPORTED: 'PAYMENT_METHOD_UNSUPPORTED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_UNKNOWN_ORDER: 'WEBHOOK_UNKNOWN_ORDER',
  REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',
  REFUND_AMOUNT_EXCEEDS_PAYMENT: 'REFUND_AMOUNT_EXCEEDS_PAYMENT',
  REFUND_ALREADY_COMPLETED: 'REFUND_ALREADY_COMPLETED',
  // ── Promo ───────────────────────────────────────────────────────────────────
  PROMO_NOT_FOUND: 'PROMO_NOT_FOUND',
  PROMO_INACTIVE: 'PROMO_INACTIVE',
  PROMO_NOT_STARTED: 'PROMO_NOT_STARTED',
  PROMO_EXPIRED: 'PROMO_EXPIRED',
  PROMO_QUOTA_EXHAUSTED: 'PROMO_QUOTA_EXHAUSTED',
  PROMO_USER_QUOTA_EXHAUSTED: 'PROMO_USER_QUOTA_EXHAUSTED',
  PROMO_MIN_TRANSACTION_NOT_MET: 'PROMO_MIN_TRANSACTION_NOT_MET',
  PROMO_NOT_APPLICABLE: 'PROMO_NOT_APPLICABLE',
  PROMO_NOT_STACKABLE: 'PROMO_NOT_STACKABLE',
  PROMO_NEW_CUSTOMER_ONLY: 'PROMO_NEW_CUSTOMER_ONLY',
  // ── Event ───────────────────────────────────────────────────────────────────
  EVENT_NOT_PUBLISHED: 'EVENT_NOT_PUBLISHED',
  EVENT_REGISTRATION_NOT_OPEN: 'EVENT_REGISTRATION_NOT_OPEN',
  EVENT_FULL: 'EVENT_FULL',
  EVENT_WAITLIST_FULL: 'EVENT_WAITLIST_FULL',
  EVENT_ALREADY_REGISTERED: 'EVENT_ALREADY_REGISTERED',
  EVENT_REGISTRATION_NOT_CANCELLABLE: 'EVENT_REGISTRATION_NOT_CANCELLABLE',
  EVENT_HAS_REGISTRATIONS: 'EVENT_HAS_REGISTRATIONS',
  EVENT_SCHEDULE_REQUIRED: 'EVENT_SCHEDULE_REQUIRED',
  // ── Tournament & Match ──────────────────────────────────────────────────────
  TOURNAMENT_REGISTRATION_NOT_OPEN: 'TOURNAMENT_REGISTRATION_NOT_OPEN',
  TOURNAMENT_FULL: 'TOURNAMENT_FULL',
  TOURNAMENT_ALREADY_REGISTERED: 'TOURNAMENT_ALREADY_REGISTERED',
  TOURNAMENT_MIN_PARTICIPANTS_NOT_MET: 'TOURNAMENT_MIN_PARTICIPANTS_NOT_MET',
  TOURNAMENT_BRACKET_ALREADY_GENERATED: 'TOURNAMENT_BRACKET_ALREADY_GENERATED',
  TOURNAMENT_BRACKET_NOT_GENERATED: 'TOURNAMENT_BRACKET_NOT_GENERATED',
  TOURNAMENT_FORMAT_UNSUPPORTED: 'TOURNAMENT_FORMAT_UNSUPPORTED',
  MATCH_NOT_SCHEDULABLE: 'MATCH_NOT_SCHEDULABLE',
  MATCH_ALREADY_COMPLETED: 'MATCH_ALREADY_COMPLETED',
  MATCH_SCORE_INVALID: 'MATCH_SCORE_INVALID',
  MATCH_PARTICIPANTS_INCOMPLETE: 'MATCH_PARTICIPANTS_INCOMPLETE',
  MATCH_WALKOVER_REQUIRES_REASON: 'MATCH_WALKOVER_REQUIRES_REASON',
  // ── Gamification ────────────────────────────────────────────────────────────
  POINT_RULE_NOT_FOUND: 'POINT_RULE_NOT_FOUND',
  POINT_CAP_REACHED: 'POINT_CAP_REACHED',
  POINT_ADJUSTMENT_REQUIRES_REASON: 'POINT_ADJUSTMENT_REQUIRES_REASON',
  LEADERBOARD_PERIOD_CLOSED: 'LEADERBOARD_PERIOD_CLOSED',
  // ── Cafe Tenant ─────────────────────────────────────────────────────────────
  CAFE_UNIT_OCCUPIED: 'CAFE_UNIT_OCCUPIED',
  CAFE_CONTRACT_NOT_ACTIVE: 'CAFE_CONTRACT_NOT_ACTIVE',
  CAFE_INVOICE_ALREADY_PAID: 'CAFE_INVOICE_ALREADY_PAID',
  CAFE_INVOICE_VOID: 'CAFE_INVOICE_VOID',
  CAFE_PAYMENT_EXCEEDS_INVOICE: 'CAFE_PAYMENT_EXCEEDS_INVOICE',
  // ── Finance & HRIS ──────────────────────────────────────────────────────────
  JOURNAL_NOT_BALANCED: 'JOURNAL_NOT_BALANCED',
  JOURNAL_ALREADY_POSTED: 'JOURNAL_ALREADY_POSTED',
  JOURNAL_PERIOD_LOCKED: 'JOURNAL_PERIOD_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ATTENDANCE_ALREADY_CLOCKED_IN: 'ATTENDANCE_ALREADY_CLOCKED_IN',
  ATTENDANCE_NOT_CLOCKED_IN: 'ATTENDANCE_NOT_CLOCKED_IN',
  SHIFT_ASSIGNMENT_CONFLICT: 'SHIFT_ASSIGNMENT_CONFLICT',
  // ── Media ───────────────────────────────────────────────────────────────────
  MEDIA_KIND_UNSUPPORTED: 'MEDIA_KIND_UNSUPPORTED',
  MEDIA_CONTENT_TYPE_UNSUPPORTED: 'MEDIA_CONTENT_TYPE_UNSUPPORTED',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_NOT_UPLOADED: 'MEDIA_NOT_UPLOADED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',

  // ── Warning-only (docs/04 § 5 "Katalog warning code") ─────────────────────
  PRICE_CHANGED: 'PRICE_CHANGED',
  PROMO_SUPERSEDED_BY_BETTER_OFFER: 'PROMO_SUPERSEDED_BY_BETTER_OFFER',
  DISCOUNT_CLAMPED: 'DISCOUNT_CLAMPED',
  BEYOND_BOOKING_HORIZON: 'BEYOND_BOOKING_HORIZON',
  COUNT_OMITTED_FOR_PERFORMANCE: 'COUNT_OMITTED_FOR_PERFORMANCE',
  STANDINGS_NOT_APPLICABLE: 'STANDINGS_NOT_APPLICABLE',
  TIE_UNRESOLVED: 'TIE_UNRESOLVED',
  WORKER_DEGRADED: 'WORKER_DEGRADED',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]

/**
 * HTTP status per kode error, persis seperti kolom "HTTP" di docs/04 § 5.
 * Warning-only tidak ada di sini — ia dikirim pada response 2xx.
 */
export const ERROR_HTTP_STATUS = {
  // ── Umum ────────────────────────────────────────────────────────────────────
  VALIDATION_ERROR: 422,
  MALFORMED_REQUEST: 400,
  UNAUTHENTICATED: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_REVOKED: 401,
  FORBIDDEN: 403,
  NOT_RESOURCE_OWNER: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  GONE: 410,
  RATE_LIMITED: 429,
  IDEMPOTENCY_KEY_REUSED: 409,
  PRECONDITION_FAILED: 409,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  UPSTREAM_ERROR: 502,
  FEATURE_DISABLED: 403,
  // ── Slot & Court ────────────────────────────────────────────────────────────
  SLOT_ALREADY_CLAIMED: 409,
  SLOT_NOT_ALIGNED: 422,
  SLOT_OUTSIDE_OPERATING_HOURS: 422,
  SLOT_IN_PAST: 422,
  SLOT_TOO_FAR_AHEAD: 422,
  SLOTS_NOT_CONTIGUOUS: 422,
  SLOT_COUNT_OUT_OF_RANGE: 422,
  COURT_NOT_BOOKABLE: 422,
  COURT_HAS_FUTURE_CLAIMS: 422,
  VENUE_CLOSED: 422,
  MIXED_BOOKING_DATE: 422,
  // ── Pricing ─────────────────────────────────────────────────────────────────
  PRICE_RULE_NOT_FOUND: 422,
  QUOTE_ITEM_LIMIT_EXCEEDED: 422,
  ADDON_NOT_APPLICABLE: 422,
  // ── Booking ─────────────────────────────────────────────────────────────────
  BOOKING_HOLD_EXPIRED: 410,
  BOOKING_NOT_CANCELLABLE: 409,
  BOOKING_ALREADY_PAID: 409,
  BOOKING_ALREADY_CANCELLED: 409,
  BOOKING_ALREADY_CHECKED_IN: 409,
  BOOKING_NOT_CHECKED_IN: 409,
  GUEST_CONTACT_REQUIRED: 422,
  // ── Payment & Refund ────────────────────────────────────────────────────────
  PAYMENT_NOT_PENDING: 409,
  PAYMENT_ALREADY_PAID: 409,
  PAYMENT_EXPIRED: 410,
  PAYMENT_AMOUNT_MISMATCH: 422,
  PAYMENT_METHOD_UNSUPPORTED: 422,
  WEBHOOK_SIGNATURE_INVALID: 401,
  WEBHOOK_UNKNOWN_ORDER: 404,
  REFUND_NOT_ALLOWED: 409,
  REFUND_AMOUNT_EXCEEDS_PAYMENT: 422,
  REFUND_ALREADY_COMPLETED: 409,
  // ── Promo ───────────────────────────────────────────────────────────────────
  PROMO_NOT_FOUND: 404,
  PROMO_INACTIVE: 422,
  PROMO_NOT_STARTED: 422,
  PROMO_EXPIRED: 410,
  PROMO_QUOTA_EXHAUSTED: 409,
  PROMO_USER_QUOTA_EXHAUSTED: 409,
  PROMO_MIN_TRANSACTION_NOT_MET: 422,
  PROMO_NOT_APPLICABLE: 422,
  PROMO_NOT_STACKABLE: 409,
  PROMO_NEW_CUSTOMER_ONLY: 422,
  // ── Event ───────────────────────────────────────────────────────────────────
  EVENT_NOT_PUBLISHED: 404,
  EVENT_REGISTRATION_NOT_OPEN: 409,
  EVENT_FULL: 409,
  EVENT_WAITLIST_FULL: 409,
  EVENT_ALREADY_REGISTERED: 409,
  EVENT_REGISTRATION_NOT_CANCELLABLE: 409,
  EVENT_HAS_REGISTRATIONS: 409,
  EVENT_SCHEDULE_REQUIRED: 422,
  // ── Tournament & Match ──────────────────────────────────────────────────────
  TOURNAMENT_REGISTRATION_NOT_OPEN: 409,
  TOURNAMENT_FULL: 409,
  TOURNAMENT_ALREADY_REGISTERED: 409,
  TOURNAMENT_MIN_PARTICIPANTS_NOT_MET: 422,
  TOURNAMENT_BRACKET_ALREADY_GENERATED: 409,
  TOURNAMENT_BRACKET_NOT_GENERATED: 409,
  TOURNAMENT_FORMAT_UNSUPPORTED: 422,
  MATCH_NOT_SCHEDULABLE: 409,
  MATCH_ALREADY_COMPLETED: 409,
  MATCH_SCORE_INVALID: 422,
  MATCH_PARTICIPANTS_INCOMPLETE: 409,
  MATCH_WALKOVER_REQUIRES_REASON: 422,
  // ── Gamification ────────────────────────────────────────────────────────────
  POINT_RULE_NOT_FOUND: 404,
  POINT_CAP_REACHED: 409,
  POINT_ADJUSTMENT_REQUIRES_REASON: 422,
  LEADERBOARD_PERIOD_CLOSED: 409,
  // ── Cafe Tenant ─────────────────────────────────────────────────────────────
  CAFE_UNIT_OCCUPIED: 409,
  CAFE_CONTRACT_NOT_ACTIVE: 409,
  CAFE_INVOICE_ALREADY_PAID: 409,
  CAFE_INVOICE_VOID: 409,
  CAFE_PAYMENT_EXCEEDS_INVOICE: 422,
  // ── Finance & HRIS ──────────────────────────────────────────────────────────
  JOURNAL_NOT_BALANCED: 422,
  JOURNAL_ALREADY_POSTED: 409,
  JOURNAL_PERIOD_LOCKED: 409,
  ACCOUNT_INACTIVE: 422,
  ATTENDANCE_ALREADY_CLOCKED_IN: 409,
  ATTENDANCE_NOT_CLOCKED_IN: 409,
  SHIFT_ASSIGNMENT_CONFLICT: 409,
  // ── Media ───────────────────────────────────────────────────────────────────
  MEDIA_KIND_UNSUPPORTED: 422,
  MEDIA_CONTENT_TYPE_UNSUPPORTED: 422,
  MEDIA_TOO_LARGE: 422,
  MEDIA_NOT_UPLOADED: 409,
  STORAGE_UNAVAILABLE: 502,
} as const satisfies Record<string, number>

export type HttpErrorCode = keyof typeof ERROR_HTTP_STATUS

/** Kode yang boleh muncul di `meta.warnings` pada response 2xx. */
export const WARNING_CODE = {
  PRICE_CHANGED: 'PRICE_CHANGED',
  PROMO_QUOTA_EXHAUSTED: 'PROMO_QUOTA_EXHAUSTED',
  PROMO_NOT_FOUND: 'PROMO_NOT_FOUND',
  PROMO_NOT_APPLICABLE: 'PROMO_NOT_APPLICABLE',
  PROMO_SUPERSEDED_BY_BETTER_OFFER: 'PROMO_SUPERSEDED_BY_BETTER_OFFER',
  DISCOUNT_CLAMPED: 'DISCOUNT_CLAMPED',
  BEYOND_BOOKING_HORIZON: 'BEYOND_BOOKING_HORIZON',
  COUNT_OMITTED_FOR_PERFORMANCE: 'COUNT_OMITTED_FOR_PERFORMANCE',
  STANDINGS_NOT_APPLICABLE: 'STANDINGS_NOT_APPLICABLE',
  SLOT_OUTSIDE_OPERATING_HOURS: 'SLOT_OUTSIDE_OPERATING_HOURS',
  TIE_UNRESOLVED: 'TIE_UNRESOLVED',
  WORKER_DEGRADED: 'WORKER_DEGRADED',
} as const

export type WarningCode = (typeof WARNING_CODE)[keyof typeof WARNING_CODE]
